version: '3.8'

services:
    webapi:
        image: ${DOCKER_REGISTRY}webapi
        build:
            context: .
            dockerfile: WebApi/Dockerfile
        ports:
          - "5000:5000"
    proxy:
        image: nginx:latest
        volumes:
          - ./WebApi/nginx.conf:/etc/nginx/nginx.conf
        depends_on: 
          - webapi
        ports:
          - "4000:4000"
        