version: '3.8'

services:
    webapi:
        image: ${DOCKER_REGISTRY}webapi
        build:
            context: .
            dockerfile: WebApi/Dockerfile
        environment:
          WEBAPI_OMDBAPIKEY: ${WEBAPI_OMDBAPIKEY}
          WEBAPI_JWT_KEY: ${WEBAPI_JWT_KEY}
          WEBAPI_JWT_ISSUER: ${WEBAPI_JWT_ISSUER}
          WEBAPI_JWT_AUDIENCE: ${WEBAPI_JWT_AUDIENCE}
          WEBAPI_USER_USERNAME: ${WEBAPI_USER_USERNAME}
          WEBAPI_USER_PASSWORD: ${WEBAPI_USER_PASSWORD}
        ports:
          - "5000:5000"
    proxy:
        image: nginx:latest
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./Client:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - webapi
        links:
            - client
        ports:
          - "8080:80"          
          - "4000:4000"
    client:
        image: php:7.4-fpm        
        volumes:
            - ./Client:/code
        