version: '3.8'

services:
    webapi:
        image: ${DOCKER_REGISTRY}webapi
        build:
            context: .
            dockerfile: WebApi/Dockerfile
        environment:
          WEBAPI_OMDBAPIKEY: ${WEBAPI_OMDBAPIKEY}
          WEBAPI_JWT_KEY: ${WEBAPI_JWT_KEY}
          WEBAPI_JWT_ISSUER: ${WEBAPI_JWT_ISSUER}
          WEBAPI_JWT_AUDIENCE: ${WEBAPI_JWT_AUDIENCE}
          WEBAPI_USER_USERNAME: ${WEBAPI_USER_USERNAME}
          WEBAPI_USER_PASSWORD: ${WEBAPI_USER_PASSWORD}
        ports:
          - "5000:5000"
    client:
        image: ${DOCKER_REGISTRY}client
        build:
            context: .
            dockerfile: Client/Dockerfile
        ports:
          - "5001:9000"        
    proxy:
        image: nginx:latest
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on: [webapi, client]
        ports:
          - "4000:4000"
        